version: '3.1'
services:

  prometheus:
    network_mode: host
    ports:
      - 9090:9090
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    network_mode: host
    image: grafana/grafana:latest
    ports:
      - 3000:3000

    

